name: Check code quality before merge to master

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Check code base before merge to master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log
        run: echo ${GITHUB_REF##*/}

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Set up npm
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run lint css
        run: npm run lint-css

      - name: Run compile
        run: npm run compile

  deploy-stage:
    needs: lint
    name: Deploy to stage server
    runs-on: ubuntu-latest
    if: ${GITHUB_REF##*/}==develop

    steps:
      - name: Run build
        run: npm run build:stage

      - name: Set up sshpass and npm
        run: |
          sudo apt-get install sshpass
          npm install

      - name: Deploy on stage server
        run: sshpass -p ${{ secrets.STAGE_SERVER_PASS }} rsync -e "ssh -o StrictHostKeyChecking=no" -rltzh -O --delete dist/rubic/ ${{ secrets.STAGE_SERVER_USER }}@${{ secrets.STAGE_SERVER_HOST }}:/var/www/stage_rubic_exchange/frontend

